### ISSUE TITLE
Android12 EMAS配置变化说明

### ISSUE THREAD

**Issue by evan0204** [evan0204/react-native-aliyun-emas#1]
EMAS通道参数需要从原来的从Java类中转移到项目的AndroidManifest.xml文件中进行配置

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2827261/158734657-fb8d46f2-6a99-48cd-9f53-5af402e0e887.png">

新老方法对比：(+为新办法)
<img width="645" alt="image" src="https://user-images.githubusercontent.com/2827261/158734370-800f0fa9-1656-4c86-bb51-66b6d70d8316.png">

新的配置示例：
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/2827261/158734522-50fd2bb4-ba47-49a8-884f-59bf9add46e3.png">

**Comment by breezes1** [comment]
是否可以更新一下MainApplication.java 文件及 AliyunPushModule.java的完整代码

**Comment by evan0204** [comment]
> 是否可以更新一下MainApplication.java 文件及 AliyunPushModule.java的完整代码

这个是readme中描述的一致，除了上面所说的变动外，其他都一样

之前由于npm管理机制问题没有发布上去，刚才npm包已经发布好了
