### ISSUE TITLE
安卓初始化方法隐私政策不允许在刚启动时调用

### ISSUE THREAD

**Issue by caijiami** [evan0204/react-native-aliyun-emas#2]
this.initCloudChannel(this);这个方法安卓可以单独封装进行调用吗，现在隐私政策挺严格的，大佬可以教一下吗

**Comment by evan0204** [comment]
> this.initCloudChannel(this);这个方法安卓可以单独封装进行调用吗，现在隐私政策挺严格的，大佬可以教一下吗

做一个判定，如果没有同意隐私协议则不初始化通知通道即可
<img width="800" alt="image" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">

**Comment by caijiami** [comment]
> > this.initCloudChannel这个方法可以单独进行调用吗，现在隐私很严格的，大佬吗？
> 
> 做一个甄别，如果同意不同意隐私协议不主动通知 <img alt="图片" width="800" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">

大佬 可以看下您的桥接代码吗，我不会桥接封装这个方法，感谢

**Comment by evan0204** [comment]
> > > this.initCloudChannel这个方法可以单独进行调用吗，现在隐私很严格的，大佬吗？
> > 
> > 
> > 做一个甄别，如果同意不同意隐私协议不主动通知 <img alt="图片" width="800" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">
> 
> 大佬 可以看下您的桥接代码吗，我不会桥接封装这个方法，感谢

initCloudChannel就是官方提供的源码，没有任何改动，这个js的逻辑就是控制什么时候开始初始化，获取相关权限的开关

**Comment by caijiami** [comment]
> > > > this.initCloudChannel这个方法可以单独进行调用吗，现在隐私很严格的，大佬吗？
> > > 
> > > 
> > > 做一个甄别，如果同意不同意隐私协议不主动通知 <img alt="图片" width="800" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">
> > 
> > 
> > 大佬 可以看下您的桥接代码吗，我不会桥接封装这个方法，感谢
> 
> initCloudChannel就是官方提供的源码，没有任何改动，这个js的逻辑就是控制什么时候开始初始化，获取相关权限的开关

大佬您是用插件的还是 阿里云官网单独集成的，我看插件里的模块没有封装这个方法呀

**Comment by evan0204** [comment]
> > > > > this.initCloudChannel这个方法可以单独进行调用吗，现在隐私很严格的，大佬吗？
> > > > 
> > > > 
> > > > 做一个甄别，如果同意不同意隐私协议不主动通知 <img alt="图片" width="800" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">
> > > 
> > > 
> > > 大佬 可以看下您的桥接代码吗，我不会桥接封装这个方法，感谢
> > 
> > 
> > initCloudChannel就是官方提供的源码，没有任何改动，这个js的逻辑就是控制什么时候开始初始化，获取相关权限的开关
> 
> 大佬您是用插件的还是 阿里云官网单独集成的，我看插件里的模块没有封装这个方法呀

插件和官网文档要结合一起来看的

**Comment by caijiami** [comment]
> > > > > > this.initCloudChannel这个方法可以单独进行调用吗，现在隐私很严格的，大佬吗？
> > > > > 
> > > > > 
> > > > > 做一个甄别，如果同意不同意隐私协议不主动通知 <img alt="图片" width="800" src="https://user-images.githubusercontent.com/2827261/177120725-6f264b30-c960-46e0-9b94-4d6244aef325.png">
> > > > 
> > > > 
> > > > 大佬 可以看下您的桥接代码吗，我不会桥接封装这个方法，感谢
> > > 
> > > 
> > > initCloudChannel就是官方提供的源码，没有任何改动，这个js的逻辑就是控制什么时候开始初始化，获取相关权限的开关
> > 
> > 
> > 大佬您是用插件的还是 阿里云官网单独集成的，我看插件里的模块没有封装这个方法呀
> 
> 插件和官网文档要结合一起来看的
大佬 能否教下小弟，怎么结合的，感激不尽
